# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLM-demo-2-production',
                'doc_host': 'https://laugustyniak.github.io',
                'git_url': 'https://github.com/laugustyniak/LLM-demo-2-production',
                'lib_path': 'LLM_demo_2_production'},
  'syms': { 'LLM_demo_2_production.social_media_automator.app': {},
            'LLM_demo_2_production.social_media_automator.autogpt': {},
            'LLM_demo_2_production.social_media_automator.mrkl': {},
            'LLM_demo_2_production.social_media_automator.qa': {}}}
