# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLM-demo-2-production',
                'doc_host': 'https://laugustyniak.github.io',
                'git_url': 'https://github.com/laugustyniak/LLM-demo-2-production',
                'lib_path': 'LLM_demo_2_production'},
  'syms': { 'LLM_demo_2_production.chat_interfaces.autogpt': {},
            'LLM_demo_2_production.chat_interfaces.generate_sm_content': {},
            'LLM_demo_2_production.chat_interfaces.mrkl': {},
            'LLM_demo_2_production.chat_interfaces.qa': {},
            'LLM_demo_2_production.llms_intro': { 'LLM_demo_2_production.llms_intro.get_completion': ( '00_llm_intro/intro_to_llms.html#get_completion',
                                                                                                       'LLM_demo_2_production/llms_intro.py'),
                                                  'LLM_demo_2_production.llms_intro.get_completion_from_messages': ( '00_llm_intro/intro_to_llms.html#get_completion_from_messages',
                                                                                                                     'LLM_demo_2_production/llms_intro.py')}}}
